rpm -qa | grep binutils-2.*
rpm -qa | grep compat-libstdc++-33*
rpm -qa | grep elfutils-libelf*
rpm -qa | grep gcc-4.*
rpm -qa | grep gcc-c++-4.*
rpm -qa | grep glibc-2.*
rpm -qa | grep glibc-common-2.*
rpm -qa | grep glibc-devel-2.*
rpm -qa | grep glibc-headers-2.*
rpm -qa | grep ksh*
rpm -qa | grep libaio-0.*
rpm -qa | grep libaio-devel-0.*
rpm -qa | grep libgomp-4.*
rpm -qa | grep libgcc-4.*
rpm -qa | grep libstdc++-4.*
rpm -qa | grep libstdc++-devel-4.*
rpm -qa | grep make-3.*
rpm -qa | grep sysstat-7.*
rpm -qa | grep unixODBC-2.*
rpm -qa | grep unixODBC-devel-2.*
rpm -qa | grep numactl-devel-*
rpm -qa | grep oracleasm*el5xen*
rpm -qa | grep oracleasm*el5debug*
rpm -qa | grep oracleasm-support*
rpm -qa | grep oracleasmlib*
sysctl -a | grep net.ipv4.ip_forward
sysctl -a | grep net.ipv4.conf.default.rp_filter
sysctl -a | grep net.ipv4.conf.default.accept_source_route
sysctl -a | grep kernel.sysrq
sysctl -a | grep kernel.core_uses_pid
sysctl -a | grep net.ipv4.tcp_syncookies
sysctl -a | grep kernel.msgmnb
sysctl -a | grep kernel.msgmax
sysctl -a | grep kernel.shmmax
sysctl -a | grep kernel.shmall
sysctl -a | grep fs.aio-max-nr
sysctl -a | grep fs.file-max
sysctl -a | grep kernel.shmmn
sysctl -a | grep kernel.sem
sysctl -a | grep net.ipv4.ip_local_port_range
sysctl -a | grep net.core.rmem_default
sysctl -a | grep net.core.rmem_max
sysctl -a | grep net.core.wmem_default


